In [1]:
# importng libraries 
import pandas as pd 
import numpy as np 
import tensorflow as tf 


In [2]:
# checking tensorflow
tf.__version__

'2.19.0'

In [3]:
!pip install numpy==1.26.4 --upgrade --force-reinstall
!pip install --upgrade --force-reinstall scipy scikit-learn

  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.2
    Uninstalling numpy-2.3.2:
      Successfully uninstalled numpy-2.3.2


  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.17.0 requires ml-dtypes<0.5.0,>=0.3.1, but you have ml-dtypes 0.5.3 which is incompatible.
tensorflow-intel 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.29.5 which is incompatible.
tensorflow-intel 2.17.0 requires tensorboard<2.18,>=2.17, but you have tensorboard 2.19.0 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached scipy-1.16.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
  Using cached scikit_learn-1.7.1-cp311-cp311-win_amd64.whl.metadata (11 kB)
  Using cached numpy-2.3.2-cp311-cp311-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scipy-1.16.1-cp311-cp311-win_amd64.whl (38.6 MB)
Using cached scikit_learn-1.7.1-cp311-cp311-win_amd64.whl (8.9 MB)
Using cached joblib-1.5.1-py3-none-any.whl (307 kB)
Using cached numpy-2.3.2-cp311-cp311-win_amd64.whl (13.1 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 3.6.0
    Uninstalling threadpoolctl-3.6.0:
      Successfully uninstalled threadpoolctl-3.6.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninst

  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.2 which is incompatible.
tensorflow-intel 2.17.0 requires ml-dtypes<0.5.0,>=0.3.1, but you have ml-dtypes 0.5.3 which is incompatible.
tensorflow-intel 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.3.2 which is incompatible.
tensorflow-intel 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 5.29.5 which is incompatible.
tensorflow-intel 2.17.0 requires tensorboard<2.18,>=2.17, but you have tensorboard 2.19.0 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m

In [4]:
# importing the data 
df = pd.read_csv("D:\study\Deep learning\study\Churn_Modelling.csv")
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
# encoding categorical to numerical data 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[: ,2] = le.fit_transform(x[:,2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(sparse_output=False), [1])], 
    remainder='passthrough'
)

x = np.array(ct.fit_transform(x))



In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
# Splitting data into training and testing :-
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2 , random_state = 0)

In [11]:
# feature scaling :-
from sklearn. preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
''' PART TWO BUILDING ANN '''

' PART TWO BUILDING ANN '

In [13]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu' , ))
ann.add(tf.keras.layers.Dense(units = 8 , activation = 'relu' , ))
ann.add(tf.keras.layers.Dense(units = 1 , activation = 'sigmoid' , ))


In [14]:
ann.compile(optimizer = 'adam' , loss ='binary_crossentropy' , metrics =['accuracy'] )

In [15]:
ann.fit(x_train, y_train , batch_size = 32 , epochs = 100 )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6242 - loss: 0.6535
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.7971 - loss: 0.4803
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.8004 - loss: 0.4467
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.7984 - loss: 0.4299
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.8051 - loss: 0.4159
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8213 - loss: 0.4016
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8370 - loss: 0.3866  
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8457 - loss: 0.3743
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8510 - loss: 0.3659
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8528 - loss: 0.3607
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8526 - loss: 0.3567
Epoch 12/100
250/250 ━━━━━━━━━━

In [16]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy on test data:", acc)


Confusion Matrix:
 [[1528   67]
 [ 204  201]]
Accuracy on test data: 0.8645


In [18]:
results = np.concatenate(
    (y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1
)
print("Predicted | Actual")
print(results[:20])

Predicted | Actual
[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [19]:
new_customer = [[600, "France", "Male", 40, 3, 60000, 2, 1, 1, 50000]]
new_customer[0][2] = 1 if new_customer[0][2] == "Male" else 0
new_customer = ct.transform(new_customer)
new_customer = sc.transform(new_customer)
prediction = ann.predict(new_customer)
prediction = (prediction > 0.5)

print("Will the customer leave?", "Yes" if prediction else "No")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
Will the customer leave? No


In [21]:
# Predict on test data
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)  # convert probabilities into 0 or 1


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [22]:
import numpy as np

# Actual distribution
actual_leave = np.sum(y_test == 1)
actual_stay = np.sum(y_test == 0)

# Predicted distribution
pred_leave = np.sum(y_pred == 1)
pred_stay = np.sum(y_pred == 0)

print("Actual Leave:", actual_leave)
print("Actual Stay:", actual_stay)
print("Predicted Leave:", pred_leave)
print("Predicted Stay:", pred_stay)


Actual Leave: 405
Actual Stay: 1595
Predicted Leave: 268
Predicted Stay: 1732


In [23]:
total = len(y_test)

print("Actual Leave %:", (actual_leave / total) * 100)
print("Actual Stay %:", (actual_stay / total) * 100)
print("Predicted Leave %:", (pred_leave / total) * 100)
print("Predicted Stay %:", (pred_stay / total) * 100)


Actual Leave %: 20.25
Actual Stay %: 79.75
Predicted Leave %: 13.4
Predicted Stay %: 86.6
